apiVersion: 1

datasources:
  - name: InfluxDB_BESS
    type: influxdb
    uid: bess-influx-01
    access: proxy
    url: http://influxdb3-core:8181
    database: iot-lab
    isDefault: true
    jsonData:
      httpMode: GET
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Token apiv3_c6ehjXu-2i7JP6fvQk3EXUfWEXsDZP6ON92rgoN-z0BK858VQ6vZjpYvrPjfJ1ruDCZ1pA9lW3ZwKoNIrYQ-dw"
